# Generated by Django 3.2.18 on 2023-05-18 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('cost', models.FloatField(verbose_name='Cena')),
                ('publicationDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 18, 27, 13, 24260))),
                ('expirationDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 18, 27, 13, 25216))),
            ],
        ),
    ]
